### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by brandondove** [wpengine/headless-framework#121]
The first link, "Enabling WordPress post previews" is a broken link in the [Learn more](https://github.com/wpengine/headless-framework/tree/canary/docs/getting-started#learn-more) section of the [Getting Started](https://github.com/wpengine/headless-framework/tree/canary/docs/getting-started) page.

I think it's supposed to go to https://github.com/wpengine/headless-framework/tree/canary/docs/previews.

**Comment by mindctrl** [comment]
@brandondove thanks for the report.

PR here: https://github.com/wpengine/headless-framework/pull/123
