### ISSUE TITLE
Ignore query strings in Next.js routing. 

### ISSUE THREAD

**Issue by octalmage** [wpengine/headless-framework#157]
Hey guys! 

Killer framework, love using it so far. I'm running into an issue using the headless-framework with Local.

Local will open URLs with a `cache-buster` query string to force browsers to load a fresh copy of the site. When Local opens the headless framework with that query string we get a 404. Removing the cache-buster query string allows the requested page to load. 

I'm wondering if we can either whitelist the `cache-buster` query string, or ignore all query strings in the routing. 

Thanks!

**Comment by octalmage** [comment]
Here's a quick screen recording to demonstrate the issue: 

https://user-images.githubusercontent.com/142006/108874634-f38a5800-75c1-11eb-97c8-37980734bc65.mov

**Comment by trevanhetzel** [comment]
I chatted with @octalmage and this issue has been resolved in the Local headless add-on with the exclusion of a query string altogether. However, the issue of random query strings throwing off the router seems to still be apparent, so this is still an issue.
