### ISSUE TITLE
Next.js app doesnt run after setup - Win 10 WSL 2

### ISSUE THREAD

**Issue by akhatri** [wpengine/headless-framework#187]
I have gone through the instructions and setup a local WP instance through WP local with an alias. I am stuck at Step 6 after running `npm run dev`

I am on Windows 10 using WSL 2 so I hope that's not the cause of this issue? 

### WP Local Setup

![WP Local config](https://user-images.githubusercontent.com/2246544/113354470-29e09300-9337-11eb-9c3f-145229524c6c.PNG)

### Next.js Error
![Next Localhost](https://user-images.githubusercontent.com/2246544/113354545-45e43480-9337-11eb-9077-b3bfd5dfa5e6.PNG)

### Apollo Error
![Apollo Error](https://user-images.githubusercontent.com/2246544/113354596-52688d00-9337-11eb-85e0-8e34c0488889.PNG)

### Local Environment File
![Local Environment file](https://user-images.githubusercontent.com/2246544/113354813-a2dfea80-9337-11eb-9f06-878474869518.PNG)

**Comment by octalmage** [comment]
Hey @akhatri! This seems like an issue with Local, not the headless-framework. It seems like there could be an issue with Local and the Atlas addon on Windows 10, I'd recommend posting this here instead: https://localwp.com/community/t/error-unable-to-provision-when-installing-headless/24935

**Comment by akhatri** [comment]
@octalmage I think the issue is with WSL 2 as it does not allow port forwarding. Details are here https://github.com/microsoft/WSL/issues/4851 for anyone who has the same issue.

Rolling back to WSL 1 for now fixes it and everything appears to be working now.
