### ISSUE TITLE
Breakout `core` Package

### ISSUE THREAD

**Issue by matt-landers** [wpengine/headless-framework#198]
This issue is in response to @wjohnsto's comment on #194 

We need to break the package up with the first package being `core` which should include (but not limited to):
The core package includes:

- Authentication and authorization
  - OAuth handlers
  - JWT Auth
  - Preview support
- Data fetching
  - Retrieve WP data based on the URL scheme
  - Fetch custom queries
  - Compose queries from fragments so that components can let the framework know the data it requires
  - Provide a mechanism for mutations
- Gutenberg block processing
  - Communication between WP and the frontend
  - Shared styles
  - Configuration
  - Data changes

**Comment by wjohnsto** [comment]
I have a working branch and package for this here: https://github.com/wpengine/headless-framework/tree/feat-core/packages/core

**Comment by wjohnsto** [comment]
The initial work for broking out the package is done as of #215. There is also #214 which breaks down auth. We need to break down data fetching and Gutenberg block processing further.
