### ISSUE TITLE
Breakout `react` package

### ISSUE THREAD

**Issue by matt-landers** [wpengine/headless-framework#199]
This issue is in response to @wjohnsto's comment on #194

In order to create a clear delineation of dependencies, a `react` package should be created with react specific features. Do not mix Next features in the `react` package. This package should include (but not limited to):

- Hooks for data fetching (usePost, usePosts, etc.)
- Gutenberg block processing for react components
- Mechanism for registering components with the framework
  - Provide data requirements

**Comment by blakewilson** [comment]
I have a working branch for this package here: https://github.com/wpengine/headless-framework/tree/feat-react
