### ISSUE TITLE
How should we expose other headless dependencies' modules?

### ISSUE THREAD

**Issue by blakewilson** [wpengine/headless-framework#228]
Currently, in the `next` package, we are importing modules from `@wpengine/headless-core` and `@wpengine/headless-react`, then exporting them to be consumed in `@wpengine/headless-next`. This allows us to only have a dependency of `@wpengine/headless-next` when building Next.js applications:

```js
import { authorizeHandler } from '@wpengine/headless-next'
```

However, as we add more functionality, this may start to pollute the named export. 

We could use a submodule approach where we export our needed modules under a `core` or `react` submodule, then import them like so in Next.js:

```js
import { authorizeHandler } from '@wpengine/headless-next/core'
import { HeadlessProvider } from '@wpengine/headless-next/react'
```

I think this approach helps delineate between modules better.

@matt-landers @wjohnsto Any thoughts on this?

**Comment by wjohnsto** [comment]
Another option is to not re-export from higher-level libraries. So you would end up with something like this:

```ts
import { authorizeHandler } from '@wpengine/headless-core';
import { HeadlessProvider } from '@wpengine/headless-react';
import { getNextStaticProps } from '@wpengine/headless-next';
```

**Comment by blakewilson** [comment]
> Another option is to not re-export from higher-level libraries. So you would end up with something like this:
> 
> ```ts
> import { authorizeHandler } from '@wpengine/headless-core';
> import { HeadlessProvider } from '@wpengine/headless-react';
> import { getNextStaticProps } from '@wpengine/headless-next';
> ```

Yep, I think this works best. I had this thought that we only wanted to rely on one package for some reason. I'll close this then, this is a non-issue.
