### ISSUE TITLE
Move from Apollo to gqless

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/headless-framework#262]
I came across this and think it might be useful for the framework to support a number of data fetching scenarios. Let's look into it and see how it works https://github.com/gqless/gqless

Pay specific attention to:

1. How does it work outside of React/Next?
2. How does it work with React/Next?
3. How well is SSG (and SSR/ISR) supported?
4. Is there opportunity for abstraction and additional functionality that `packages/core`, `packages/react`, and `packages/next` can provide specific to Headless WordPress?

Comment on this issue with any interesting findings. Try to include some sample code with your comments.

UPDATE: We're moving to gqless. Here is how it will work:

1. `core` will ship with a default implementation of the gqless client and WPGraphQL schema.
2. `core` will publish a function for creating the client that allows overwriting of the schema with a custom version (supports custom WPGraphQL queries)
3. `core` will also allow intercepting fetch calls to handle the request, apply headers, etc.
4. `react` will use `@gqless/react` and provide a similar level of configuration for the React gqless client as `core`
5. The example apps will provide a standard way of creating the client and providing it to the framework for use in any helper functions.

Branch for this here: https://github.com/wpengine/headless-framework/tree/feature-gqless

**Comment by blakewilson** [comment]
Just got done testing a few use cases in Next with SSG/SSR. So far, this seems like it would be useful in our framework. Here are some of my initial findings:

Take a super simple example where you would like to fetch the first 6 posts for the home page (similar to what we are doing in our examples):

```tsx
import { PropsWithServerCache } from "@gqless/react";
import { GetStaticProps } from "next";
import Link from "next/link";
import { prepareReactRender, useHydrateCache, useQuery } from "../gqless";

type PageProps = PropsWithServerCache<{}>;

export default function HomePage({ cacheSnapshot }: PageProps) {
  useHydrateCache({
    cacheSnapshot,
    shouldRefetch: false,
  });

  const query = useQuery();

  const posts = query.posts({ first: 6 });

  return (
    <div>
      <h1>My Home Page</h1>

      <h2>My recent posts</h2>
      <ul>
        {posts?.nodes?.map((post) => (
          <li key={post?.id}>
            <Link href={`/posts/${post?.slug}`}>
              <a>{post?.title()}</a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export const getStaticProps: GetStaticProps<PageProps> = async (context) => {
  const { cacheSnapshot } = await prepareReactRender(<HomePage />);

  return {
    props: {
      cacheSnapshot,
    },
  };
};
```

What is nice, is all of the GraphQL based data fetching that happens in the component is prepared and fetched server side/build time thanks to `prepareReactRender()`. This is an interesting concept where you provide the component and it's props to `prepareReactRender` server side, then an optimized query is formed/executed from that.

In my testing, `prepareReactRender()` works well in SSG and SSR. Additionally, this is not Next.js specific functionality, so this should work in any SSR/SSG react framework.

The above code is an example that follows closely to gqless' docs, but we could abstract a lot of this logic into our framework. For example, take the `getStaticProps()` from above:

```tsx
export const getStaticProps: GetStaticProps<PageProps> = async (context) => {
  const { cacheSnapshot } = await prepareReactRender(<HomePage />);

  return {
    props: {
      cacheSnapshot,
    },
  };
};
```

We could abstract most of this logic into an interface like `getNextStaticProps`:
```tsx
export const getStaticProps: GetStaticProps<PageProps> = async (context) => {
  return await getNextStaticProps(HomePage, { title: 'Home Page' });
};
```

`getNextStaticProps` could then look something like:

```tsx
import { prepareReactRender} from "../gqless";

export const getNextStaticProps = async (Component, props) => {
  const { cacheSnapshot } = await prepareReactRender(<Component {...props} />);

  return {
    props: {
      cacheSnapshot,
      ...props,
    },
  };
};
```

Some findings that may factor into the adoption:
* There is some initial setup to construct the schema and query fetcher. I believe this could be packaged into core/abstracted though.
* In terms of working in React, our hooks like `usePost`, `usePosts`, etc. would be able to easily use the `query` object from `useQuery` to fetch data without having any data fetching logic on the server side thanks to `prepareReactRender`. I think this is a huge win for making things more user friendly.

**Comment by wjohnsto** [comment]
Here's are my thoughts:

1. gqless is definitely what we want to use, and seems the most flexible way to fetch data from any GQL API
2. We can generate a default schema as well as gqless client in `core`, then we can generate a React client in `react`.
3. We can expose a way to create the client and pass in your own schema as well as a way to override/extend headers for each request, which will allow use with custom GQL queries/mutations as well as authentication headers.
