### ISSUE TITLE
Implement pagination for examples/next/getting-started categories

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/headless-framework#277]
There's no support at the moment for this in the framework, so let's see what it takes to do manually and how the framework can accommodate this. Refer to #235 for the example layout of paginated categories.

Log bugs as-needed.

**Comment by blakewilson** [comment]
Previously, our category pagination implementation looked like this:
```
├─ category/
│  ├─ [categorySlug].tsx <-- category/featured
│  ├─ [paginationTerm]/
│  │  ├─ [categoryCursor].tsx <-- category/featured/[before|after]/tbsda==
```

With a pagination URL that looked like: `/category/after/cursor`.

However, this is not allowed in Next.js as the `categorySlug` and `paginationTerm` are both dynamic routes.

So, the structure has been modified to the below:

```
├─ category/
│  ├─ [categorySlug].tsx <-- category/featured
│  ├─ page/
│  │  │  ├─ [paginationTerm]/
│  │  │  |  ├─[categoryCursor].tsx <-- category/featured/[before|after]/tbsda==
```

This will result in the following URL: `/category/page/after/cursor`.

**Comment by wjohnsto** [comment]
Let's keep this for category and go with `postSlug` for posts, this way the app dev can see both implementations and choose what they want to use.
