### ISSUE TITLE
Is there any workaround for not yet supported unions in gqless?

### ISSUE THREAD

**Issue by CptCompiler** [wpengine/headless-framework#346]
Is there any way to query unions with the faust package?

something like this is pretty common in wordpress, isn't it?

```
       template {
          ... on  Template_FullwidthLayout{
            templateName
            someOtherFields
          }
        }
```

https://github.com/gqless/gqless/issues/215

**Comment by wjohnsto** [comment]
You can always include another client (Apollo, react-query, graphql-request, normal fetch, etc) in your application and make queries with it. I think this is the temporary workaround before there is support in gqless.
