### ISSUE TITLE
WP/GraphQL endpoint

### ISSUE THREAD

**Issue by moonmeister** [wpengine/headless-framework#351]
Faust asks for the WP endpoint then adds the `/graphql` path. But I'm wanting to proxy the endpoint through a CDN like GraphCDN(https://my-app.graphcdn.app) which doesn't have the `/graphql` endpoint and I'm not sure how else that WP url is used. 

I'm recommending we allow for this use case by either not assuming the `/graphql` endpoint or allow a specific override for the graphql endpoint.

**Comment by moonmeister** [comment]
Sounds perfect.

**Comment by wjohnsto** [comment]
Maybe `gqlEndpoint`
