### ISSUE TITLE
TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined

### ISSUE THREAD

**Issue by krishaamer** [wpengine/headless-framework#361]
<img width="1065" alt="Screenshot 2021-07-22 at 15 15 05" src="https://user-images.githubusercontent.com/54409/126637508-506534fe-7f0c-49b8-81e0-8cc1d007502e.png">
While trying to deploy the canary gqless nextjs example project to Vercel I get `Error occurred prerendering page "/404 TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined"`.

**Comment by blakewilson** [comment]
Hey @krishaamer 👋 

It looks like this error has occurred in Next.js in the past when there is a `<Link>` component without an `href` prop.
https://github.com/vercel/next.js/issues/16107

Additionally, could you try running `npm run build` locally to see if this is reproducible? That way we can rule out if this is a Vercel related issue.

**Comment by wjohnsto** [comment]
Without seeing your code I can't be sure, but you might be running into this error because you are have a value that you are passing to `href` in your `<Link />` that ends up being `null` or `undefined`. I typically do something like this to avoid that problem:

```tsx
<Link href={value ?? ''}>...</Link>
```

The above code will make sure there is always something sent into `href` and avoid the error you're getting.

**Comment by Fraganya** [comment]
Thanks @wjohnsto, Inspecting my Links worked for me.

**Comment by iamnbutler** [comment]
Wild – This was a `next/link` problem in case anyone else ends up here a year+ later. Next link should probably have some earlier catching of this.

**Comment by peperoli** [comment]
A similar error `TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.` can also happen when Link has a `shallow` prop which is not (yet) supported in the app router.

**Comment by Bem20-james** [comment]
thanks @wjohnsto  inspecting my links worked for me too..

**Comment by kaf-lamed-beyt** [comment]
I had a similar error. But the culprit isn't the Link component.  It was because I got the import path of a component wrong. 

```jsx
import CountViews from "@components/Button"
```

I used the appropriate path and the error was gone. 

```jsx
import CountViews from "@components/viewCounter"
```

**Comment by theCompanyDream** [comment]
> A similar error `TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.` can also happen when Link has a `shallow` prop which is not (yet) supported in the app router.

Does that mean that next/link doesn't really support relative links?

**Comment by cording12** [comment]
> A similar error `TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.` can also happen when Link has a `shallow` prop which is not (yet) supported in the app router.

This was exactly my error. I was using the next/link component where the href was a variable, however, the variable was potentially undefined. I coerced it originally: `<Link href={DOMAIN as string}>`. This worked locally, but in my build the variable was not in my .env, therefore being undefined and causing the error.

I stopped coercing and coded it properly (it was unnecessary for me anyway) and that fixed the issue.

**Comment by renatodex** [comment]
> Hey @krishaamer 👋
> 
> It looks like this error has occurred in Next.js in the past when there is a `<Link>` component without an `href` prop. [vercel/next.js#16107](https://github.com/vercel/next.js/issues/16107)
> 
> Additionally, could you try running `npm run build` locally to see if this is reproducible? That way we can rule out if this is a Vercel related issue.

After a few package upgrades, I was getting this Build error, and I was literally checking every 54 different APIs of my project only to find out that the damn next/link throws an AUTH variable error when Href is missing.
I was like.......WAT ?

![image](https://github.com/wpengine/faustjs/assets/68507/6239cbff-c8b4-4ba9-9446-e10cdee2e479)

**Comment by shyamkumawat088** [comment]
In my case i was using `Router.push(url)` where url was undefined, which is causing this issue.

you can check the logic and make sure url is not `null` or `undefined`.
or you can pass a fallback as well like `Router.push(url || '')`.

**Comment by fortune710** [comment]
> Wild – This was a `next/link` problem in case anyone else ends up here a year+ later. Next link should probably have some earlier catching of this.

Another year later and Next link still doesn't have a way of catching this

**Comment by absolutegravitas** [comment]
lol and closed as if this regarded issue doesnt need to be fixed...

**Comment by cbHasib** [comment]
It's end of 2024 and still I spent my 2 hrs to figure out this error! 
lol. nextjs rocks!

**Comment by kuangbeibei** [comment]
2025 Now, still there

**Comment by PriyabrataMo** [comment]
> Without seeing your code I can't be sure, but you might be running into this error because you are have a value that you are passing to `href` in your `<Link />` that ends up being `null` or `undefined`. I typically do something like this to avoid that problem:
> 
> <Link href={value ?? ''}>...</Link>
> The above code will make sure there is always something sent into `href` and avoid the error you're getting.

Thanks man me and my team were debugging it for 3 hrs 
your advice worked!!!

**Comment by BurhanWRTeam** [comment]
> Without seeing your code I can't be sure, but you might be running into this error because you are have a value that you are passing to `href` in your `<Link />` that ends up being `null` or `undefined`. I typically do something like this to avoid that problem:
> 
> <Link href={value ?? ''}>...</Link>
> The above code will make sure there is always something sent into `href` and avoid the error you're getting.

Thank you! 👍 
In my case error is created by the <Link> component from the "next/router" as the href passed was undefined

**Comment by sk-thakor** [comment]
thank you so much i sucessfully half day waste of debugging solve this issue.
