### ISSUE TITLE
Bug: Breaks Polylang URLs

### ISSUE THREAD

**Issue by moonmeister** [wpengine/headless-framework#390]
## The current behavior

After some recent updates polylang URLS are bing broken by the Headless  Plugin. I have 3 languages. English, German, and French. French and German URLs should be prefixed with their respective language code (e.g. `/fr/posts/my-post`). This is the case when the plugin is disabled but upon enabling the plugin the prefix is removed and there is no more language prefix. 

This did work and one point. If I had to guess it was working on 0.5.5 of the plugin, not sure when it broke exactlly. I'll do some testing to see if I can when it broke and what the change was. 

## Applicable Versions

- WordPress version: 5.8, 
- Headless plugin: 0.5.7

## The expected behavior

I'd expect the headless plugin not to break Polylang language prefixes.

**Comment by moonmeister** [comment]
🤔 doesn't seem to be working with 0.5.5 either.

**Comment by moonmeister** [comment]
Okay. Figured this one out. The basic fix is changing the priority of our URL replacement so it's executed after the polylang link modifier happens. This makes sense as any plugins are going to assume standard WP links and not our Headless links. 
 
 Is a reasonable fix to change all of our link modifier priorities too `100` (or anything high) to try and make sure they happen after any plugin modifies the link?

**Comment by moonmeister** [comment]
FYI: the polylang link modifiers are set with a priority of `20`.

**Comment by mindctrl** [comment]
> Is a reasonable fix to change all of our link modifier priorities too 100 (or anything high) to try and make sure they happen after any plugin modifies the link?

👍 seems reasonable to me.
