### ISSUE TITLE
Docs: gqty.com should be gqty.dev

### ISSUE THREAD

**Issue by justlevine** [wpengine/headless-framework#407]
Heads up - most if not all of the GQty links in the documentation direct to [`https://gqty.com`](https://gqty.com). The correct domain name is [`https://gqty.dev`](https://gqty.dev).

**Comment by blakewilson** [comment]
Hey @justlevine,

Thanks for bringing this up! I've updated the docs to reflect the correct URL. The changes should be live soon.
